# Generated by Django 4.0.8 on 2023-11-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroModel',
        ),
    ]
